# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a890929fdd45b028e20b25ebd7792dd141ae7c164f802121a433904788959c3b64198268c2ed8949c04ab9bde646c4d861a99e4dc8d0f62ef4b6e7b567f3990

test:
  secret_key_base: 99c56eaa694de066e413f979f0afabb1a0805aabe1b80acff65b4c975197440513385618d9226adc01ed49538807efa22c6d1305d1f498152a91aecc4e345e22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
